name: flutter_native_splash_lego
description: "native splash screen for flutter project."
#publish_to: 'none'
repository: https://github.com/flutter-lego/flutter_native_splash_lego

version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: #@add
  gap: #@add
  june_flow_util:
  styled_widget: #@add
  modal_bottom_sheet: #@add
  keyboard_attachable: #@add
  flutter_zoom_drawer: #@add
  flutter_screenutil:
  bot_toast:
  flutter_native_splash: #@add

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  screenutil_lego: #@add
  bot_toast_lego: #@add
  widget_binding_lego: #@add

flutter:
  assets:
    - assets/lego/flutter_native_splash_lego/
  uses-material-design: true

#@add start
flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/lego/flutter_native_splash_lego/splash_icon.png"
  image: assets/lego/flutter_native_splash_lego/splash_icon.png

  color_dark: "#ffffff"
  ##background_image_dark: "assets/lego/flutter_native_splash_lego/splash_icon.png"
  image_dark: assets/lego/flutter_native_splash_lego/splash_icon.png

  #android: false
  #ios: false
  #web: false

  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center

  fullscreen: true
#@add end

topics:
  - lego